### ISSUE TITLE
Invoke-MgConvertFirewallRules.ps1

### ISSUE THREAD

**Issue by hib1000** [ennnbeee/oddsandendpoints-scripts#1]
Hi i'm getting the following error from the browser on the second auth;

Request Id: 021c9282-1f45-49ae-aff7-8e1ba9195100
Correlation Id: cba95e9f-219f-474b-ac84-2a82b5374541
Timestamp: 2024-07-22T15:37:33Z
Message: AADSTS650053: The application 'Microsoft Graph Command Line Tools' asked for scope 'Test0' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'. Contact the app vendor.

Any help would be greatly appreciated

**Comment by hib1000** [comment]
Closed because i'm an idiot... your GPO to Endpoint Security script already does the conversion to settings catalog!!

**Comment by ennnbeee** [comment]
> Closed because i'm an idiot... your GPO to Endpoint Security script already does the conversion to settings catalog!!

hahah, don't worry about it mate...gave me a chance to have a look at this script again.

I retested and it seemed to be OK when running it using something like the below:

`.\Invoke-MgConvertFirewallRules.ps1 -tenantId 36019fe7-a342-4d98-9126-1b6f94904ac7 -policyName 'CO_FW_Rules' -oldFirewallPolicies 'Legacy_FW_Rule1','Legacy_FW_Rule2','Legacy_FW_Rule3'`

The other script is just updated to support the new authentication method, I don't think it, or the original, create Settings Catalog firewall rule policies.

**Comment by hib1000** [comment]
That's really weird then... do you think intune converted it under the hood
somehow? I used your script to import them directly from a device with
rules applied from Group Policy, but they're showing in Endpoint Security
as "MDM, MicrosoftSense" and they're definitely settings catalog

**Comment by ennnbeee** [comment]
Yeah that is odd, I'll have an investigate when I've got some time this week.

**Comment by hib1000** [comment]
Cheers, your scripts have saved me untold hours effort!

**Comment by hib1000** [comment]
Ok quick update, I have no idea what converted those policies! The
conversion script is still failing for the same reason on a policy that is
DEFINITELY 'mdm'

**Comment by hib1000** [comment]
...and then by magic it just changed!  Something is going on in th
background!

**Comment by ennnbeee** [comment]
Yeah it looks as though Microsoft is doing something with them, just tested, and checked my old migrated profiles, and they're now all settings catalog profiles...they're ugly, but they're settings catalog at least 😂

**Comment by hib1000** [comment]
Why are they ugly? Is anything missing?

**Comment by ennnbeee** [comment]
Nah nothing missing, just a lot of padding when you view them in the portal.

**Comment by ennnbeee** [comment]
I've just created a new set of policies using the migration tool, I'll check on them later on to see if they magically convert.

**Comment by hib1000** [comment]
Well ... I don't know how to feel about this. I can't wait to explain to
people that it works by "magic". Either way, thanks for your amazing help
and support.

**Comment by ennnbeee** [comment]
I've done a quick write up on the topic https://memv.ennbee.uk/posts/firewall-rule-policy-conversion/

**Comment by hib1000** [comment]
That's brilliant, thank you very much.

What an absolute rollercoaster this has been, from the original script
disappearing from MS's documentation, to your blog, it been the longest
month of my life!

**Comment by hib1000** [comment]
Can I suggest one last improvement for the import script... error handling
when local/remote ips have too many entries. The log it creates doesn't
explain which rules need fixing and it'd be nice if it imported the rest
and ignored those... or split them across multiple rules
