### ISSUE TITLE
LAPS Policy cannot be imported

### ISSUE THREAD

**Issue by Tafelhase** [ennnbeee/oddsandendpoints-scripts#2]
The policy file CIS (L1) Windows LAPS - Windows 11 Intune 3.0.1.json cannot be imported and fails with an error. The error displayed in intune is generic and simply states the import failed.

**Comment by ennnbeee** [comment]
As this is file was exported using https://github.com/Micke-K/IntuneManagement you can't import it directly to Intune, have a read https://memv.ennbee.uk/posts/windows-cis-patching-gaps-part3/#local-administrator-password-solution for more information.
